### ISSUE TITLE
Creating 2 identical Services in a single accessory

### ISSUE THREAD

**Issue by rjcarlson49** [homebridge/homebridge-plugin-template#6]
I have a WindowCovering (shades) plugin and I am trying to add 2 switches (Services) to act as simple open/close buttons within the WindowCovering accessory code. This is not ideal, but I can't find any other Service that meets the need. The plugin is based on this template. The addition of the 2 switches is done via code copied from the comment on line 39 of platformAccessory.ts.

Here's the code:

    this.swServiceOpen = this.accessory.getService(this.platform.Service.Switch)
                    || this.accessory.addService(this.platform.Service.Switch, this.displayName + ' Open', 'Open');
    this.swServiceClose = this.accessory.getService(this.platform.Service.Switch)
                    || this.accessory.addService(this.platform.Service.Switch), this.displayName + ' Close', 'Close';
    this.swServiceOpen.displayName = this.displayName + ' Open';
    this.swServiceOpen.subtype = 'Open';
    this.swServiceClose.displayName = this.displayName + ' Close';
    this.swServiceClose.subtype = 'Close';

I added the last 4 lines because I saw that "solution" in an Issue comment. It did not help. When I look at the Accessories on the Homebridge UI, I see only the Open switches, not the Close ones. The single switches that appear are at first "within" the WindowCovering icon, but can be separated with a setting.

It also appears that when a get or set is called on the switch from Homekit, the listener for both switches is being called. When the second listener calls the callback, it crashes with the "already called that callback" error. So, I have simply removed temporarily one of the two callbacks so I can keep debugging. This seems to keep me afloat for now.

I posted this first as an issue under Homebridge itself, but was just pointed at code that looks just like mine. This has not helped so far.

How do I properly set the subtype? Clearly these two Switch service creations are not properly differentiated in the code.

**Comment by rjcarlson49** [comment]
I have also tried nuking the cache so that the "addService" would be invoked rather that getService, to ensure that the subtype was included in the call. This did not help.

**Comment by rjcarlson49** [comment]
If you want to see the full code, it's now public at https://github.com/rjcarlson49/homebridge-dooya-0.

**Comment by rjcarlson49** [comment]
I tried this code:
 
    this.swServiceClose = <Service>this.accessory.getService(this.platform.Service.Switch);
    if (!this.swServiceClose) {
      this.swServiceClose = new this.platform.Service.Switch(this.displayName + ' Close', 'Close');
      if (this.swServiceOpen) {
        this.logCh('New Close Switch Service');
      } else {
        this.logCh('New Close Switch Service -- Failed!');
      }
    } 
    
After deleting the Accessory from the cache I ran this. It reports that the Switch services are created, but the switches do not show up in Home or the Accessories page on the HB web UI.

**Comment by rjcarlson49** [comment]
OK, I finally found code that works.

    this.service = this.accessory.getService(this.platform.Service.WindowCovering) 
                || this.accessory.addService(this.platform.Service.WindowCovering);
    
    this.swServiceOpen = <Service>this.accessory.getServiceById(this.platform.Service.Switch, 'Open');
    if (!this.swServiceOpen) {
      this.swServiceOpen = new this.platform.Service.Switch(this.displayName + ' Open', 'Open');
      if (this.swServiceOpen) {
        this.swServiceOpen = this.accessory.addService(this.swServiceOpen);
        this.logCh('New Open Switch Service');
      } else {
        this.logCh('New Open Switch Service -- Failed!');
      }
    } 
    this.swServiceClose = <Service>this.accessory.getServiceById(this.platform.Service.Switch, 'Close');
    if (!this.swServiceClose) {
      this.swServiceClose = new this.platform.Service.Switch(this.displayName + ' Close', 'Close');
      if (this.swServiceClose) {
        this.swServiceClose = this.accessory.addService(this.swServiceClose);
        this.logCh('New Close Switch Service');
      } else {
        this.logCh('New Close Switch Service -- Failed!');
      }
    } 
   
When restoring a multiple service, you have to search for the cached service with getServiceByID, passing the service type and subtype. When creating the service the first time, use the equivalent of 'new  this platform.Service.Switch' passing display name and subtype. The service must then be added with .addService.

**Comment by Kristian8606** [comment]
I'm trying to create a temperature accessory that contains temperature and humidity.
How to do it?

**Comment by Kristian8606** [comment]
` this.serviceTemp = this.accessory.getService(this.platform.Service.TemperatureSensor) || this.accessory.addService(this.platform.Service.TemperatureSensor, 'Temperature');
      this.serviceTemp.getCharacteristic(this.platform.Characteristic.CurrentTemperature)
        .on('get', this.handleCurrentTemperatureGet.bind(this));`

      `this.serviceHum` = this.accessory.getService(this.platform.Service.HumiditySensor) || this.accessory.addService(this.platform.Service.HumiditySensor, 'Humidity');
      this.serviceHum.getCharacteristic(this.platform.Characteristic.CurrentRelativeHumidity)
        .on('get', this.handleCurrentRelativeHumidityGet.bind(this));`

**Comment by rjcarlson49** [comment]
I am not an expert as this is my first plugin. However, I don't believe you can achieve that look. Each tile in Home that has multiple services within the accessory has a setting "Show as separate tiles". When this is disabled, my tile shows the state of only one Characteristic within the accessory.

**Comment by jvmahon** [comment]
Is this for controlling a "simple" binary Open / Close shade motor? As opposed to the type that "HomeKit" expects which is percentage-based?

If so, consider the solution I put in my plugin here: https://www.npmjs.com/package/homebridge-smartshades

This plugin works with  NEO Smart shade controller which I use to control "basic" motors with one-way communications and only Open / Closed  command. Because the motors have only one-way communication, the NEO controller doesn't know if another device has opened or closed the shades - thus, the NEO is stateless in that it doesn't actually know what position the shade is in. So what I did was to show the shade in the iOS Home application as if it was always half-open (i.e., at 50%). Then, if you swipe up, it opens, swipe down, it closes, and you can still tell Siri "Open Shade" or "Close Shade" and it works.  

Code is on github - https://github.com/jvmahon/homebridge-smartshades

Particularly relevant code is at lines 100-190 of the file index.js.  
Lines 158-165 are activated when you swipe the iOS Home shade symbol all the way to 0%. This then activates the close function by sending a command (line 161) to the NEO Smart controller to close the shade.  Lines 162-163 then start a 25 second timer (my estimate of how long it takes the shade to move). At the end of the timer, lines 163-164 "fake resets" the position to 50%.

Lines 169-178 perform a similar function but for "Open".

If you swipe from the 50% mid-point to 51-99 or 1-49, nothing happens -- its only if you swipe fully open or fully closed that the open or closed function is triggered.

Note that the NEO shade controller is a pretty basic device. It can't handle too many request at once (I recall the specs say not to send more than 1 command every 250 mSeconds. So, just in case I do a "Siri Close All Shades" which tiggers about a half-dozen shades to close at once, I use the queue library (line 6) to create a queue (line 8) to queue send commands (line 128) which are then executed at a 500 mSecond interval (line 124). 

Happy to give you a further explanation if it helps.

**Comment by oznu** [comment]
Added example showing how to create multiple services of the same type:

https://github.com/homebridge/homebridge-plugin-template/blob/master/src/platformAccessory.ts#L54-L70

**Comment by Kristian8606** [comment]
Thanks
